### ISSUE TITLE
first slide of a chapter's dot does not fill

### ISSUE THREAD

**Issue by njkirkpatrick** [alberti42/Keynote-Progress-Bar#2]
The first slide of a new chapter has the highlighted chapter font and size, but the dot does not fill in. The second slide of the chapter jumps to two dots being filled. Am I doing something wrong? Here's the presenter note I use for the first slide to set everything up:

{progress bar; start; RemoveAll=false; ChapterSeparation=60; FontFamily=Helvetica-Light; FlipUpsideDown=false; FontFamilyHighlightedChapter=Helvetica-Bold; NumberOfDots=37; DotSize=7; ContourWidth=0.2; FontSize=18; chapter=Background; CompletedDotFillColor={255,255,255,100}; UncompletedDotFillColor={121,121,121,100}; CompletedDotStrokeColor={255,255,255,0}; UncompletedDotStrokeColor={121,121,121,0};CompletedTextColor={255,255,255,100}; UncompletedTextColor={255,255,255,100} BaselineOffset=0; Margins={0,40,0,40}; SameAsPreviousAutomatic=true; SetAllPositionsEqual=true; PreserveExistingImages=false; skipDrawing; duration=0}

Then I eventually have a slide with presenter notes like this:
{progress bar; chapter= First chapter; duration= 1}

this slide will not have a dot filled in, but the second slide will have two.

**Comment by alberti42** [comment]
Did you check with the example https://github.com/alberti42/Keynote-Progress-Bar/raw/main/Docs/Examples/Example-Keynote-Progress-Bar.key whether it works for you? Did you add the command for the last slide?

I will have to try with your strings. I don't have time right now. Can you check whether the example works?

**Comment by alberti42** [comment]
Ok, perhaps I have an idea what bothers you. It is about the algorithm or logic running behind the script.

In the present implementation, the first slide of a chapter is shown with empty dots. The last slide of a chapter is shown with all dots filled. The slides in between are shown with dots filled according to estimated progress based on the stated duration of the slide.

I paste here the other tools I developed but not released yet on the front page, which I use to rehearse talks. I run a presentation with the rehearse script. This writes down a file with the duration of each slide. You can also pause the presentation by exiting the presentation mode. It only records the effective duration when you are in presentation mode. Then, when I am happy with the presentation, I run the other script that applies automatically the duration to each slide based on what was recorded.

[Archiv.zip](https://github.com/user-attachments/files/17430415/Archiv.zip)

I can imagine that one would like to support a different type of algorithm to number the slides, perhaps something that is based on some explicit statement like a command `AddNewDot`. There are a lot of possibilities.

If the two dots really bother you, let's discuss what good alternative algorithms to fill the dots could be.

**Comment by njkirkpatrick** [comment]
I can understand that. I'm basically using it where each slide is either duration=1 or duration=0. I ended up just faking it by overlaying a dot with the completedDotFillColor on top. I really appreciate all your work on this project! It's incredibly useful.

**Comment by alberti42** [comment]
Cool. I still think that it would be a good thing to extend the range of commands to support other ways to make the dots appear. I can imagine that not everybody loves the idea of dots representing the actual duration. I don't have much time right now to program a new logic for how dots appear.

I am glad that you found a way to fake the progress as you wished. Yes, setting the duration of certain slides to 0 makes the trick to give you full control of when a new dot should appear. However, I presume you still need to count how many times you set `duration=1` and then update the total number of dots accordingly.

**Comment by njkirkpatrick** [comment]
Yes counting the slides is a bit tedious, but it gets the job done. Thanks again for your work on this!On Oct 20, 2024, at 8:28 AM, Andrea Alberti ***@***.***> wrote:﻿
Cool. I still think that it would be a good thing to extend the range of commands to support other ways to make the dots appear. I can imagine that not everybody loves the idea of dots representing the actual duration. I don't have much time right now to program a new logic for how dots appear.
I am glad that you found a way to fake the progress as you wished. Yes, setting the duration of certain slides to 0 makes the trick to give you full control of when a new dot should appear. However, I presume you still need to count how many times you set duration=1 and then update the total number of dots accordingly.
